// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MicrosoftNewsAPI.SDK.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MicrosoftNewsClientODataResponseMsnTagsDataModelTagEntityLibMarket
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftNewsClientODataResponseMsnTagsDataModelTagEntityLibMarket
        /// class.
        /// </summary>
        public MicrosoftNewsClientODataResponseMsnTagsDataModelTagEntityLibMarket()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftNewsClientODataResponseMsnTagsDataModelTagEntityLibMarket
        /// class.
        /// </summary>
        /// <param name="odatacontext">Gets or sets the OdataContext
        /// Defines the odataContext</param>
        /// <param name="value">Gets or sets the Value
        /// Defines the value</param>
        public MicrosoftNewsClientODataResponseMsnTagsDataModelTagEntityLibMarket(string odatacontext = default(string), IList<MsnTagsDataModelTagEntityLibMarket> value = default(IList<MsnTagsDataModelTagEntityLibMarket>))
        {
            Odatacontext = odatacontext;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the OdataContext
        /// Defines the odataContext
        /// </summary>
        [JsonProperty(PropertyName = "@odata.context")]
        public string Odatacontext { get; set; }

        /// <summary>
        /// Gets or sets the Value
        /// Defines the value
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MsnTagsDataModelTagEntityLibMarket> Value { get; set; }

    }
}
