// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MicrosoftNewsAPI.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MicrosoftNewsClientODataErrorItem
    {
        /// <summary>
        /// Initializes a new instance of the MicrosoftNewsClientODataErrorItem
        /// class.
        /// </summary>
        public MicrosoftNewsClientODataErrorItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MicrosoftNewsClientODataErrorItem
        /// class.
        /// </summary>
        /// <param name="errorMessage">Gets or sets the ErrorMessage
        /// Defines the errorMessage</param>
        public MicrosoftNewsClientODataErrorItem(string errorMessage = default(string))
        {
            ErrorMessage = errorMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the ErrorMessage
        /// Defines the errorMessage
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; set; }

    }
}
