// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MicrosoftNewsAPI.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MsnTagsDataModelTagEntityLibArtifactDataProviderSummary
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataProviderSummary class.
        /// </summary>
        public MsnTagsDataModelTagEntityLibArtifactDataProviderSummary()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataProviderSummary class.
        /// </summary>
        public MsnTagsDataModelTagEntityLibArtifactDataProviderSummary(string id = default(string), string name = default(string), string adNetworkId = default(string), MsnTagsDataModelTagEntityLibArtifactDataImage logo = default(MsnTagsDataModelTagEntityLibArtifactDataImage), string subscriptionUrl = default(string))
        {
            Id = id;
            Name = name;
            AdNetworkId = adNetworkId;
            Logo = logo;
            SubscriptionUrl = subscriptionUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "adNetworkId")]
        public string AdNetworkId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logo")]
        public MsnTagsDataModelTagEntityLibArtifactDataImage Logo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionUrl")]
        public string SubscriptionUrl { get; set; }

    }
}
