// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MicrosoftNewsAPI.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MsnTagsDataModelTagEntityLibArtifactDataCloseCaption
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataCloseCaption class.
        /// </summary>
        public MsnTagsDataModelTagEntityLibArtifactDataCloseCaption()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataCloseCaption class.
        /// </summary>
        /// <param name="locale">Gets or sets the locale.</param>
        /// <param name="href">Gets or sets the HREF.</param>
        public MsnTagsDataModelTagEntityLibArtifactDataCloseCaption(string locale = default(string), string href = default(string))
        {
            Locale = locale;
            Href = href;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the locale.
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// Gets or sets the HREF.
        /// </summary>
        [JsonProperty(PropertyName = "href")]
        public string Href { get; set; }

    }
}
