// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MicrosoftNewsAPI.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MsnTagsDataModelTagEntityLibArtifactDataAudioMetadata
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataAudioMetadata class.
        /// </summary>
        public MsnTagsDataModelTagEntityLibArtifactDataAudioMetadata()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataAudioMetadata class.
        /// </summary>
        /// <param name="playTime">Gets or sets the play time.</param>
        /// <param name="attribution">Gets or sets the audio
        /// attribution.</param>
        /// <param name="copyright">Gets or sets the copyright.</param>
        public MsnTagsDataModelTagEntityLibArtifactDataAudioMetadata(int? playTime = default(int?), string attribution = default(string), string copyright = default(string))
        {
            PlayTime = playTime;
            Attribution = attribution;
            Copyright = copyright;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the play time.
        /// </summary>
        [JsonProperty(PropertyName = "playTime")]
        public int? PlayTime { get; set; }

        /// <summary>
        /// Gets or sets the audio attribution.
        /// </summary>
        [JsonProperty(PropertyName = "attribution")]
        public string Attribution { get; set; }

        /// <summary>
        /// Gets or sets the copyright.
        /// </summary>
        [JsonProperty(PropertyName = "copyright")]
        public string Copyright { get; set; }

    }
}
