// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MicrosoftNewsAPI.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MsnTagsDataModelTagEntityLibArtifactDataTagEvaluationGroup
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataTagEvaluationGroup class.
        /// </summary>
        public MsnTagsDataModelTagEntityLibArtifactDataTagEvaluationGroup()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataTagEvaluationGroup class.
        /// </summary>
        /// <param name="vector">Gets or sets Vector</param>
        /// <param name="source">Gets or sets Source</param>
        public MsnTagsDataModelTagEntityLibArtifactDataTagEvaluationGroup(string vector = default(string), string source = default(string))
        {
            Vector = vector;
            Source = source;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets Vector
        /// </summary>
        [JsonProperty(PropertyName = "vector")]
        public string Vector { get; set; }

        /// <summary>
        /// Gets or sets Source
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; set; }

    }
}
