// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MicrosoftNewsAPI.SDK.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MsnTagsDataModelTagEntityLibArtifactDataFocalRegion
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataFocalRegion class.
        /// </summary>
        public MsnTagsDataModelTagEntityLibArtifactDataFocalRegion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataFocalRegion class.
        /// </summary>
        /// <param name="x1">Gets or sets X1</param>
        /// <param name="x2">Gets or sets X2</param>
        /// <param name="y1">Gets or sets Y1</param>
        /// <param name="y2">Gets or sets Y2</param>
        public MsnTagsDataModelTagEntityLibArtifactDataFocalRegion(int? x1 = default(int?), int? x2 = default(int?), int? y1 = default(int?), int? y2 = default(int?))
        {
            X1 = x1;
            X2 = x2;
            Y1 = y1;
            Y2 = y2;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets X1
        /// </summary>
        [JsonProperty(PropertyName = "x1")]
        public int? X1 { get; set; }

        /// <summary>
        /// Gets or sets X2
        /// </summary>
        [JsonProperty(PropertyName = "x2")]
        public int? X2 { get; set; }

        /// <summary>
        /// Gets or sets Y1
        /// </summary>
        [JsonProperty(PropertyName = "y1")]
        public int? Y1 { get; set; }

        /// <summary>
        /// Gets or sets Y2
        /// </summary>
        [JsonProperty(PropertyName = "y2")]
        public int? Y2 { get; set; }

    }
}
