// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace MicrosoftNewsAPI.SDK.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MsnTagsDataModelTagEntityLibArtifactDataVideoMetadata
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataVideoMetadata class.
        /// </summary>
        public MsnTagsDataModelTagEntityLibArtifactDataVideoMetadata()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MsnTagsDataModelTagEntityLibArtifactDataVideoMetadata class.
        /// </summary>
        /// <param name="playTime">Gets or sets the play time.</param>
        /// <param name="closedCaptions">Gets or sets the closed
        /// captions.</param>
        /// <param name="externalVideoFiles">Gets or sets the external video
        /// files.</param>
        public MsnTagsDataModelTagEntityLibArtifactDataVideoMetadata(int? playTime = default(int?), IList<MsnTagsDataModelTagEntityLibArtifactDataCloseCaption> closedCaptions = default(IList<MsnTagsDataModelTagEntityLibArtifactDataCloseCaption>), IList<MsnTagsDataModelTagEntityLibArtifactDataExternalVideoFile> externalVideoFiles = default(IList<MsnTagsDataModelTagEntityLibArtifactDataExternalVideoFile>))
        {
            PlayTime = playTime;
            ClosedCaptions = closedCaptions;
            ExternalVideoFiles = externalVideoFiles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the play time.
        /// </summary>
        [JsonProperty(PropertyName = "playTime")]
        public int? PlayTime { get; set; }

        /// <summary>
        /// Gets or sets the closed captions.
        /// </summary>
        [JsonProperty(PropertyName = "closedCaptions")]
        public IList<MsnTagsDataModelTagEntityLibArtifactDataCloseCaption> ClosedCaptions { get; set; }

        /// <summary>
        /// Gets or sets the external video files.
        /// </summary>
        [JsonProperty(PropertyName = "externalVideoFiles")]
        public IList<MsnTagsDataModelTagEntityLibArtifactDataExternalVideoFile> ExternalVideoFiles { get; set; }

    }
}
